### ISSUE TITLE
"require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden. Variables inside are insecure.

### ISSUE THREAD

**Issue by lucasburlingham** [XENONMC-DEV/XENFRAME#1]
#### Currently on:
+ **Commit**:  45a0700f0e63073ac185e9b82e003715600b870d
+ **File**:    [index.php](https://github.com/XENONMC-DEV/XENFRAME/blob/45a0700f0e63073ac185e9b82e003715600b870d/index.php)
+ **LineNum**: [10](https://github.com/XENONMC-DEV/XENFRAME/blob/45a0700f0e63073ac185e9b82e003715600b870d/index.php#L10)
    

Variables are dangerous when it comes to injection. @XfaonXE , please look at this.

(Sorry xfaon for the ping btw.)

**Comment by XfaonXE** [comment]
There is nothing wrong with the open variable, only vendor code can access it, user input cant be provided from the index.php but only the request handler and controllers
