### ISSUE TITLE
[no-multiple-toplevel-headings] Don’t use multiple top level headings (1:1)

### ISSUE THREAD

**Issue by lucasburlingham** [XENONMC-DEV/XENFRAME#3]
#### Currently on:
+ **Commit**:  597c43a0c2e37304cdb417810132d65fd5b72272
+ **File**:    [README.md](https://github.com/XENONMC-DEV/XENFRAME/blob/597c43a0c2e37304cdb417810132d65fd5b72272/README.md)
+ **LineNum**: [4](https://github.com/XENONMC-DEV/XENFRAME/blob/597c43a0c2e37304cdb417810132d65fd5b72272/README.md#L4)

**Comment by XfaonXE** [comment]
Fixed
